Vauxoo/pre-commit-vauxoo

src/pre_commit_vauxoo/cfg/.prettierrc.yml
The "xmlSelfClosingSpace" parameter is a flag:
- https://github.com/prettier/plugin-xml/blob/ae911c9d287f229df5f/src/plugin.ts#L16
It is not able to ignore it
It was disabled in order to avoid a big diff but for projects using the OCA standard
where this flag is enabled it is generating a big diff too
In order to stick to OCA configuration this flag is enabled
=> [REF] prettierrc.yml: Enable xmlSelfClosingSpace

.github/workflows/github-actions.yml
In order to get faster builds re-using the latest packages installed on pre-commit
=> [REF] github: Set pre-commit cache

src/pre_commit_vauxoo/cli.py
Using click 6.6 shows the following traceback:
File "pre_commit_vauxoo/cli.py", line 85, in <module>
type=click.Choice(["mandatory", "optional", "fix", "all"], case_sensitive=False),
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'
=> [REF] click: Remove incompatible parameter for all click versions

.github/workflows/github-actions.yml
The GH action to publish pypi `pypa/gh-action-pypi-publish@release/v1`
spends 0.5m building a docker image
but it could be released faster using directly `twine` and it is cached in pip
Only trigger GH actions for stable branch master and PRs to branch
and tags to auto-release to pypi
Even include pypi* branches in order to be able to test upload to pypi in stable
Continuation from https://github.com/Vauxoo/pre-commit-vauxoo/pull/42 but stable branch to test
=> [REF] CI: Faster pypi publish, remove "needs" to run parallel but only trigger for stable branches and PRs and tags

src/pre_commit_vauxoo/cli.py, src/pre_commit_vauxoo/pre_commit_vauxoo.py
Invert the parameter to no-overwrite in order to use it as flag since it is false by default
and remove short name parameter for flags
Before this PR to avoid overwrite configuration files you needed using:
- `--overwrite=false`
But it was `true` by default
After this PR you set `--no-overwrite` without value only to disable a default feature
=> [FIX] pre_commit_vauxoo: Fix duplicate '-w' parameter

src/pre_commit_vauxoo/cli.py, src/pre_commit_vauxoo/pre_commit_vauxoo.py, tests/test_pre_commit_vauxoo.py
Prefer using precommit_hooks_type as help says
It is better to disable or enable many configuration files instead of confusing with a extra parameter to overwrite this parameter
=> [REF] pre_commit_vauxoo: Deprecate PRECOMMIT_AUTOFIX in pro PRECOMMIT_HOOKS_TYPE=all

src/pre_commit_vauxoo/pre_commit_vauxoo.py
Each hook has it status and color related
But mandatory was using the autofixes status by mistake
=> [REF] pre_commit_vauxoo: Mandatory green even if mandatory are red

src/pre_commit_vauxoo/cfg/pyproject.toml, src/pre_commit_vauxoo/cli.py, src/pre_commit_vauxoo/pre_commit_vauxoo.py, tests/test_pre_commit_vauxoo.py
Add extra parameter to skip it
--skip-string-normalization
And it is set as it in the black configuration file
String normalization is enabled by default now
So you will need to disable it manually where it is used if you don't like it
=> [REF] pre_commit_vauxoo: Enable black's string normalization and add extra parameter to disable it

.github/workflows/github-actions.yml
The environment variable was add from:
- https://git.vauxoo.com/devops/vxci/-/settings/ci_cd - Section "Variables"
Literally, it is pressing the button to rebuild the last stable pipeline:
- <img width="788" alt="Screen Shot 2022-09-12 at 17 17 18" src="https://user-images.githubusercontent.com/6644187/189769096-cf7a783f-08cc-43df-a4c1-c8c616568d49.png">
=> [REF] CI: Trigger pipeline to dockerv if new release

src/pre_commit_vauxoo/pre_commit_vauxoo.py
Sometimes the local environment is different to CI
e.g. python version
So, the auto-fixes could be different between CI and local environment
Currently, if locally is not reformatting but CI there is not an easy way to fix it
A hard way is to install the same python version or check what is different (e.g. pre-commit-vauxoo version, black version, cache and so on)
Could be great to show a diff with the changes in order to apply it locally only if the auto-fixes did changes from the CI
Close to the following section:
pre-commit-vauxoo/src/pre_commit_vauxoo/pre_commit_vauxoo.py](https://github.com/Vauxoo/pre-commit-vauxoo/blob/914148ae4c8a6bfba3246451612de8283471f4b3/src/pre_commit_vauxoo/pre_commit_vauxoo.py#L253
This MR show diff with changes made in autofixes.
Fix …
=> [IMP] pre_commit_vauxoo: show diff with changes made in autofixes

src/pre_commit_vauxoo/cfg/.flake8
Because it's handled by black and it doesn't consider black syntax like:
chunk = records[index : index + chunk_size]
=> [REF] cfg/.flake8: ignore E203 (whitespace before ':')

src/pre_commit_vauxoo/cfg/.pylintrc, src/pre_commit_vauxoo/cfg/.pylintrc-optional
New way:
- `test_account_move_out_refund.py:128:8: (super-with-arguments) Consider using Python 3 style super() without arguments`
Notice `128:8` where the number `8` is the column
The editors are able to open the file in the line and column where the check was raised
* The `msg-id` was removed since it is invalid to disable comments
* The `object` was removed in order to get a shorter message
=> [REF] pylintrc: Add 'column' to message-template option and change format

tests/test_pre_commit_vauxoo.py
git old version are not compatible with this option
I think it is not even needed to use it here
=> [REF] tests: Remove git --initial-branch parameter incompatible with old git version

src/pre_commit_vauxoo/cfg/.eslintrc.json
Fix the following error
Parsing error: 'import' and 'export' may appear only with 'sourceType: module'
Fixing using the following solution:
https://github.com/AtomLinter/linter-eslint/issues/462#issuecomment-190770417
=> [FIX] eslint: Fix 'import' sentence error

src/pre_commit_vauxoo/pre_commit_vauxoo.py
If you have added to git the file `pyproject.toml` it shows the following error:
```txt
2022-12-15 18:08:48,722 INFO pre-commit-vauxoo: ------------------------- AUTOFIX CHECKS -------------------------
2022-12-15 18:08:48,723 INFO pre-commit-vauxoo: Running autofix checks (affect status build but you can autofix them locally)
2022-12-15 18:08:48,723 DEBUG pre-commit-vauxoo: Running command: pre-commit run --color=always --all -c .pre-commit-config-autofix.yaml
black....................................................................Passed
autoflake................................................................Passed
prettier (with plugin-xml)...............................................Passed
trim trailing whitespace.................................................Passed
fix end of …
```
=> [REF] pre-commit-vauxoo: Fix missing newline for pyproject.toml

src/pre_commit_vauxoo/cfg/.pre-commit-config-autofix.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config.yaml
Fixes #97. Due to historical reasons migration scripts were excluded, however starting from version 15.0 and on, they will be considered in checks. Therefore the configuration files regex were updated accordingly.
=> Include migrations script for versions 15 and higher

src/pre_commit_vauxoo/cfg/.pylintrc, src/pre_commit_vauxoo/cfg/.pylintrc-optional
This change is required, due to a change in the legal and the brand of the company, the old name was Jarsa Sistemas,
now the company brand name is Jarsa
=> [REF] pylint.conf: Update partner name as required author

src/pre_commit_vauxoo/cfg/.pre-commit-config-autofix.yaml
Fixing the following traceback:
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/odoo/.cache/pre-commit/repoap8yazcd/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
Processing /home/odoo/.cache/pre-commit/repoap8yazcd
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
error: subprocess-exited-with-error
× …
=> [FIX] pre-commit-vauxoo: Fix isort hook - RuntimeError The Poetry configuration is invalid

README.rst, src/pre_commit_vauxoo/pre_commit_vauxoo.py, test-requirements.txt, tests/test_pre_commit_vauxoo.py
This fixes #102. Previously the auto generated regex to exclude a module named "dummy" would also exclude any other module whose name started with "dummy".
The regex has been fixed and "dummy" can now be automatically excluded without excluding "dummy_subscription" or other similarly named repos.
=> [FIX] non-installable module regex

.github/workflows/github-actions.yml, src/pre_commit_vauxoo/cfg/.pre-commit-config-autofix.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml
`po-pretty-format` has been added as a new hook (on 0.0.26) to odoo-pre-commit-hooks, this commit adds this new hook with autofix enabled.
It has also been disabled from the optional configuration, since it will be already run in the autofix one.
In this release another check has also been added, to prevent tags with oe_structure as class from not having an ID.
Related to hook: https://github.com/OCA/odoo-pre-commit-hooks/pull/76
Related to issue: https://github.com/Vauxoo/pre-commit-vauxoo/issues/104
=> [IMP] update odoo-pre-commit-hooks, add po-pretty-format, oe_structure

src/pre_commit_vauxoo/cfg/.bandit, src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml
Since that Odoo's team via inbox twitter is not convinced to repair them and the entire Odoo is raising these checks Disabled since that doesn't have sense to repair all the modules but the odoo core will have the risk
=> [REF] cfg: Update bandit version and disable defusedxml checks

src/pre_commit_vauxoo/cfg/.oca_hooks-autofix.cfg, src/pre_commit_vauxoo/cfg/.oca_hooks.cfg, src/pre_commit_vauxoo/cfg/.pre-commit-config-autofix.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml
Closes #111.
All settings which can be set through a configuration file for odoo-pre-commit-hooks have been moved to their respective config file.
=> [REF] use config files for oca-hooks

src/pre_commit_vauxoo/cli.py, src/pre_commit_vauxoo/pre_commit_vauxoo.py, tests/test_pre_commit_vauxoo.py, tox.ini
Closes https://github.com/Vauxoo/pre-commit-vauxoo/issues/115.
As is the case with pylint, this commit adds support for the environment
variable `OCA_HOOKS_DISABLE_CHECKS`. Checks must be listed in it as a
comma separated list, said checks will be added to the disable section
of oca_hooks.cfg, effectively disabling them.
This lets projects disable checks through variables.sh
=> [IMP] support disabling oca hooks through env var

src/pre_commit_vauxoo/cfg/.pre-commit-config-autofix.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml
Config files have been updated to use the new release of odoo hooks.
=> [IMP] cfg: update oca odoo hooks version

tox.ini
ChangeLog requires 'pbr'
But the tox build was installing requirements manually instead of installing the test-requirements.txt file were all them are considered
=> [REF] tox: Build ChangeLog again

.github/workflows/github-actions.yml
actions/checkout was updated from v2 to v3, v2 is using Node 12 which is
deprecated and is scheduled to stop working on github pipelines.
Closes https://github.com/Vauxoo/pre-commit-vauxoo/issues/121.
=> ci: Update actions/checkout

src/pre_commit_vauxoo/cfg/.pre-commit-config-autofix.yaml
Some checks that performed the same thing (e.g. fix line endings) have been removed to leave only one. Also removed all forbid hooks that  have a remove hook available (which does the same thing and autofixes).
Closes #124.
=> [REF] Remove redundant autofix checks

src/pre_commit_vauxoo/cfg/.pre-commit-config-autofix.yaml, tests/test_pre_commit_vauxoo.py
Autofix hooks have been updated to their latest version. Biggest change involves black removing whitespaces after class/method declarations.
BREAKING CHANGE: black may generate diffs on projects
=> [IMP] cfg: update black version

src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config.yaml
The version of pylint-odoo used by hooks has been updated to its latest (v9.0.5).
=> [IMP] cfg: update pylint-odoo

src/pre_commit_vauxoo/cfg/.pre-commit-config.yaml, tests/test_pre_commit_vauxoo.py
Adds a `fail` language hook to validate filenames. This particular hook simply verifies that the filename does not contain spaces, but it can be extended to more general requirements.
=> [ADD] adds new hook: prevents files from having whitespaces in their name

src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config.yaml
New pylint-odoo version is compatible to use multiple jobs and this commit enables the option in order to run faster
However, there is a pending issue to fix:
- https://github.com/OCA/pylint-odoo/pull/512
So, consider-merging-classes-inherited could be not raised
=> [REV] pre-commit-config: Revert enable jobs for pylint hook

.github/workflows/github-actions.yml, README.rst, setup.cfg, setup.py, src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config.yaml, src/pre_commit_vauxoo/cfg/.pylintrc, src/pre_commit_vauxoo/cfg/.pylintrc-optional, src/pre_commit_vauxoo/hooks/check_deactivate_jinja.py, src/pre_commit_vauxoo/pre_commit_vauxoo.py, tests/test_pre_commit_vauxoo.py
Realted to https://github.com/OCA/pylint-odoo/pull/515
To install this version use:
- `pip install --force-reinstall -U git+https://github.com/Vauxoo-dev/pre-commit-vauxoo@main-upd-pycfg-moy.git`
=> [REF] pre_commit_vauxoo: Update pylint version

src/pre_commit_vauxoo/hooks/check_deactivate_jinja.py
"nginx_url" is a valid variable to use in the "deactivate.jinja" file
If we have more new variables in the future we have added an explicit message was used to know how to fix it
=> [REF] check_deactivate_jinja: Add "nginx_url" variable and better error message

src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config.yaml
Check release notes:
- https://pypi.org/project/pylint-odoo
v9.3.3
[FIX] prohibited-method-override: Check if caller has a func attribute (https://github.com/OCA/pylint-odoo/pull/524) [ADD] deprecated-name-get: name_get deprecated since v17 (https://github.com/OCA/pylint-odoo/pull/526) [ADD] manifest-external-assets: No external sources for assets (https://github.com/OCA/pylint-odoo/pull/525)
=> [REF] pylint_odoo: Update pylint version to v9.3.3

requirements.txt, src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config.yaml, src/pre_commit_vauxoo/cli.py
* [REF] pylint_odoo: Update pylint version to v9.3.6
Check release notes:
- https://pypi.org/project/pylint-odoo/9.3.6
[ADD] inheritable-method-string: Add check to preserve inheritability for compute, search and inverse,  (https://github.com/OCA/pylint-odoo/pull/528)
[ADD] inheritable-method-lambda: Add check to be inheritable the domain and default using lambda (https://github.com/OCA/pylint-odoo/pull/529)
[FIX] click: Pinned 'click' version where it is compatibility
New changes for 'click' package are not compatible
TODO: Update latest click version and do it compatible
=> [REF] pylint_odoo: Update pylint version to v9.3.6

src/pre_commit_vauxoo/cfg/.pre-commit-config-autofix.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml
* https://github.com/OCA/odoo-pre-commit-hooks/pull/127
- Fix https://github.com/OCA/odoo-pre-commit-hooks/issues/74
* https://github.com/OCA/odoo-pre-commit-hooks/pull/125
- A new check has been added to check for deprecated chatters in modules version 18 and above. It was also necessary to extract module version for this new check to selectively enable/disable the new check.
- Fix https://github.com/OCA/odoo-pre-commit-hooks/issues/121
And small fixes
=> [REF] cfg: Upgrade oca-odoo-pre-commit-hooks v0.1.2

src/pre_commit_vauxoo/cfg/.pre-commit-config-autofix.yaml, src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml
[REF] file-not-used: Skip option using "oca_data_manual" in the manifest file (https://github.com/OCA/odoo-pre-commit-hooks/pull/130)
=> [REF] config: Update odoo-pre-commit-hooks to v0.1.4

.github/workflows/github-actions.yml, setup.cfg, setup.py, tox.ini
Set github actions version first level value in order to use latest minor releases
=> [REF] github-actions: Use py3.14 pre-release
